src/objects/Festival__c.object
<CustomObject>
    <fields>
        <fullName>Capacity__c</fullName>
        <description>Number of persons festival can hold</description>
        <label>Capacity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Festival</label>
    <nameField>
        <label>Festival Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Festivals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestStateBatch.cls
@isTest
public class TestStateBatch 
{	
    @isTest
    public static void testMethod123()
    {
		String query='SELECT Id, Name, Capacity__c FROM Festival__c';
        String field='Capacity__c';
    
        Test.startTest();
              Database.executeBatch(new StateBatch(query,field));
        Test.stopTest();

		 StateBatch obj = new StateBatch();
    long sum=obj.returnTotal();
    System.assertEquals(0, sum);       
    }
    
}