src/objects/My_Team__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Next_Birthday__c</fullName>
        <formula>IF(  MONTH( Birthday__c ) &lt;  MONTH( TODAY() )   ,  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) ) ,  IF(MONTH( Birthday__c ) &gt;  MONTH( TODAY() ), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  IF(DAY(Birthday__c) &gt;= DAY(TODAY()), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) )) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Birthday</label>
        <type>Date</type>
    </fields>
    <label>My Team</label>
    <nameField>
        <label>My Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/testBdy.cls
public class testBdy {
    
    public static void testFunc()
    {
         Date todaydate= Date.today();
        
        My_Team__c [] teamEmail= [ SELECT  Email__c,next_birthday__c from My_Team__c where (next_birthday__c !=:todaydate) ];
        
        
        Integer len= teamEmail.size();
        
        List<String> mail = new List<String> ();
        List<Date>   nbd= new List<Date>();
        
       for(Integer i=0; i<len; i++)
        {
            mail.add(teamEmail[i].Email__c);
            nbd.add(teamEmail[i].next_birthday__c);
            
        }
        
            for(Integer i=0; i<len; i++)
            {
                System.debug(teamEmail[i].Email__c);
                System.debug(teamEmail[i].next_birthday__c);
            }    
    }
}