src/objects/My_Team__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Next_Birthday__c</fullName>
        <formula>IF(  MONTH( Birthday__c ) &lt;  MONTH( TODAY() )   ,  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) ) ,  IF(MONTH( Birthday__c ) &gt;  MONTH( TODAY() ), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  IF(DAY(Birthday__c) &gt;= DAY(TODAY()), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) )) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Birthday</label>
        <type>Date</type>
    </fields>
    <label>My Team</label>
    <nameField>
        <label>My Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestBirth.cls
public class TestBirth{
    public static void Printmail()
    {
        Date todaydate= Date.today();
        
       My_Team__c [] teamEmail= [ SELECT  Email__c,next_birthday__c from My_Team__c where (next_birthday__c !=:todaydate) ];
        
        //System.debug(teamEmail[0].Email__c);
        System.debug(teamEmail[0].next_birthday__c);
        
       Integer len= teamEmail.size();
        
        List<String> mail = new List<String> ();
        
       for(Integer i=0; i<len; i++)
        {
            mail.add(teamEmail[i].Email__c);
            
            
        }
            //EmailManager.sendMail('rahulsingh26@deloitte.com','test subject','test body');
            System.debug(mail[12]);
        
    }
}