src/objects/My_Team__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Next_Birthday__c</fullName>
        <formula>IF(  MONTH( Birthday__c ) &lt;  MONTH( TODAY() )   ,  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) ) ,  IF(MONTH( Birthday__c ) &gt;  MONTH( TODAY() ), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  IF(DAY(Birthday__c) &gt;= DAY(TODAY()), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) )) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <label>Team Member Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>My Team</label>
    <nameField>
        <label>My Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BirthdayMail.cls
global class BirthdayMail implements Schedulable
{
    String totalNames='';
    
	global void execute (SchedulableContext sc)
    {
        sendBirthdaYAlert();
    }
    
    public void sendBirthdaYAlert()
    {
        Date todaydate= Date.today();
        
       My_Team__c [] teamEmail= [ SELECT  Email__c,Next_birthday__c from My_Team__c where (next_birthday__c !=:todaydate) ];
        
        Integer len= teamEmail.size();
        
        List<String> mail = new List<String>();
        List<Date>   nbd= new List<Date>();
        
        for(Integer i=0; i<len; i++)
        {
            mail.add(teamEmail[i].Email__c);
            nbd.add(teamEmail[i].next_birthday__c);
        }
        
        for(Integer i=0; i<nbd.size(); i++)
        {
          if(nbd[i]==todaydate)
          {
              for(Integer j=0; j<len; j++)
             EmailManager.sendMail(mail[j],getSubject(),getBody()); 
          }
        }
    }
    
    public string getSubject()
    {
        
        Date todaydate= Date.today();
        My_Team__c[] name=[ SELECT  Team_Member_Name__c from My_Team__c where (next_birthday__c =:todaydate) ];
        
        List<String> bdyName= new List<String>();
        
        for(Integer i=0; i<name.size(); i++)
        {
          bdyName.add(name[i].Team_Member_Name__c);  
        }
        //Adding person names having birthday on same date
         for(Integer j=0; j<name.size(); j++)
        {
          totalNames+=bdyName[j]+' ';
        }
        String subject='Today is '+totalNames+' birthday';
        
        return subject;
    }
    
    public String getBody()
    {
        String body='Hi Team, Let\'s get together for '+totalNames+' birthday planning. Thanks Rahul :)';
        
        return body;
    }
}