src/objects/My_Team__c.object
<CustomObject>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>Birthday</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                    <default>true</default>
                    <label>Male</label>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Next_Birthday__c</fullName>
        <formula>IF(  MONTH( Birthday__c ) &lt;  MONTH( TODAY() )   ,  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) ) ,  IF(MONTH( Birthday__c ) &gt;  MONTH( TODAY() ), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  IF(DAY(Birthday__c) &gt;= DAY(TODAY()), DATE( YEAR( TODAY() ) , MONTH(Birthday__c) , DAY(Birthday__c) ),  DATE( YEAR( TODAY() )+1 , MONTH(Birthday__c) , DAY(Birthday__c) )) ) )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Next Birthday</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Team_Member_Name__c</fullName>
        <label>Team Member Name</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>My Team</label>
    <nameField>
        <label>My Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>My Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BirthdayController.cls
public class BirthdayController 
{
     My_Team__c team = new My_Team__c();
    
	public BirthdayController() 
    {
        team = [SELECT Id, Name, Birthday__c, Next_Birthday__c, Team_Member_Name__c,Gender__c FROM My_Team__c  where Next_Birthday__c >= today order by Next_Birthday__c asc limit 1];
    }

    public String getBirthDate()
    {
        String[] month = new String[]{'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul','Aug', 'Sep', 'Oct', 'Nov', 'Dec'};
        
        Date d = team.Next_Birthday__c ;
        String dt = DateTime.newInstance(d.year(), d.month(), d.day()).format('dd-MM-YYYY');
        String[] arrDate = dt.split('\\-');
        
        Integer ind = Integer.valueof(arrDate[1].trim());
        String mon = month[ind-1];
        
 		return mon+' '+arrDate[0]+', '+arrDate[2];
    }
    
    public String getPerson(){
        return team.Team_Member_Name__c;
    }
    
    public String getName(){
        return team.Name;
    }
    public String getGender(){
        return team.Gender__c;
    }
    
    public String getMessage(){
        
        Date todaydate= Date.today();
        
        if(team.Next_Birthday__c == todaydate)
            return 'True';
        else
            return 'False';
    }

   
}